services:
#  web:
#    build: .
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#      - minio

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
#    container_name: frontend-container
#    ports:
#      - "3000:3000"
#    depends_on:
#      - web

volumes:
  postgres_data: